<?php

/**
 * Implements hook_entity_info_alter().
 */
function as_dept_view_modes_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['card'] = array(
    'label' => t('Card'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['stat'] = array(
    'label' => t('Stat'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['homepage_article'] = array(
    'label' => t('Homepage Article'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['pano_slideshow'] = array(
    'label' => t('Pano Slideshow'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['quote'] = array(
    'label' => t('Quote'),
    'custom settings' => TRUE,
  );
    $entity_info['node']['view modes']['spotlight'] = array(
    'label' => t('Spotlight'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['list'] = array(
    'label' => t('List'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['directory'] = array(
    'label' => t('Directory'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['newsletter'] = array(
    'label' => t('Newsletter'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['netid'] = array(
    'label' => t('NetID'),
    'custom settings' => TRUE,
  );
  $entity_info['field_collection_item']['view modes']['media_block'] = array(
    'label' => t('Image and Text (media block)'),
    'custom settings' => TRUE,
  );
  $entity_info['field_collection_item']['view modes']['photo_gallery_one'] = array(
    'label' => t('Photo Gallery One'),
    'custom settings' => TRUE,
  );
  $entity_info['field_collection_item']['view modes']['gallery_2'] = array(
    'label' => t('Gallery 2'),
    'custom settings' => TRUE,
  );
  $entity_info['bean']['view modes']['newsletter_events'] = array(
    'label' => t('Newsletter Events'),
    'custom settings' => TRUE,
  );
}
